import { useState, useEffect, useCallback } from 'react';
import { AlertCircle, CheckCircle2, Filter, Shield, ShieldAlert, Siren } from 'lucide-react';
import IssueCard from '../components/IssueCard';
import LoadingState from '../components/LoadingState';
import CinematicScene from '../components/CinematicScene';
import { getAllIssues } from '../services/api';

const FILTER_OPTIONS = [
  { value: 'all', label: 'All Issues' },
  { value: 'critical', label: 'Critical' },
  { value: 'needs_review', label: 'Needs Review' },
  { value: 'strong', label: 'Strong' },
];

const CATEGORY_OPTIONS = [
  { value: 'all', label: 'All Categories' },
  { value: 'CHARACTER_CONTRADICTION', label: 'Character' },
  { value: 'TIMELINE_BREAK', label: 'Timeline' },
  { value: 'BROKEN_PROMISE', label: 'Promise' },
  { value: 'WORLD_RULE_VIOLATION', label: 'World Rule' },
  { value: 'RELATIONSHIP_INCONSISTENCY', label: 'Relationship' },
];

export default function Review() {
  const [issues, setIssues] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [statusFilter, setStatusFilter] = useState('all');
  const [categoryFilter, setCategoryFilter] = useState('all');

  const fetchIssues = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getAllIssues();
      setIssues(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchIssues();
  }, [fetchIssues]);

  const handleResolve = (issueId) => {
    setIssues((prev) =>
      prev.map((i) =>
        i.id === issueId
          ? { ...i, resolved: true, resolved_evidence: 'Issue addressed by creator.' }
          : i
      )
    );
  };

  const filtered = issues.filter((issue) => {
    if (statusFilter !== 'all') {
      if (issue.resolved && statusFilter !== 'resolved') return false;
      if (!issue.resolved && issue.status !== statusFilter) return false;
    }
    if (categoryFilter !== 'all' && issue.category !== categoryFilter) return false;
    return true;
  });

  const stats = {
    total: issues.length,
    critical: issues.filter((i) => !i.resolved && i.status === 'critical').length,
    needsReview: issues.filter((i) => !i.resolved && i.status === 'needs_review').length,
    resolved: issues.filter((i) => i.resolved).length,
  };

  const statCards = [
    { label: 'Total Issues', value: stats.total, color: 'text-verse-text', icon: Shield },
    { label: 'Critical', value: stats.critical, color: 'text-verse-red', icon: Siren },
    { label: 'Needs Review', value: stats.needsReview, color: 'text-verse-amber', icon: ShieldAlert },
    { label: 'Resolved', value: stats.resolved, color: 'text-verse-green', icon: CheckCircle2 },
  ];

  return (
    <div className="page-shell space-y-6">
      <section className="page-spotlight">
        <div className="relative z-10 space-y-5">
          <div className="hero-kicker mono">
            <Shield size={14} className="text-verse-red" />
            <strong>Validation Review</strong>
            <span>Evidence-backed issue triage</span>
          </div>
          <div className="space-y-3">
            <h1 className="page-title">Continuity risks, ready to fix.</h1>
            <p className="page-subtitle">
              Review findings generated by deterministic validators, with LLM-written
              explanations layered on top for creator-ready action.
            </p>
          </div>
        </div>
        <CinematicScene variant="review" compact />
      </section>

      <section className="stat-grid">
        {statCards.map(({ label, value, color, icon: Icon }) => (
          <div key={label} className="stat-card">
            <div className="flex items-center justify-between gap-3">
              <p>{label}</p>
              <Icon size={16} className={color} />
            </div>
            <strong className={color}>{value}</strong>
          </div>
        ))}
      </section>

      <section className="glass-panel p-4 md:p-5 space-y-4">
        <div className="flex items-center gap-3">
          <Filter size={15} className="text-verse-red" />
          <div>
            <h2 className="heading-md text-verse-text">Signal filters</h2>
            <p className="text-sm text-verse-text-muted">
              Narrow by severity or issue category.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          <div className="flex gap-1.5 flex-wrap">
            {FILTER_OPTIONS.map(({ value, label }) => (
              <button
                key={value}
                onClick={() => setStatusFilter(value)}
                className={`
                  filter-chip px-3 py-1.5 rounded-full text-xs font-medium transition-all
                  ${statusFilter === value
                    ? 'filter-chip-active'
                    : 'text-verse-text-muted hover:text-verse-text hover:border-verse-border-light'
                  }
                `}
              >
                {label}
              </button>
            ))}
          </div>
          <div className="h-4 w-px bg-verse-border hidden md:block" />
          <div className="flex gap-1.5 flex-wrap">
            {CATEGORY_OPTIONS.map(({ value, label }) => (
              <button
                key={value}
                onClick={() => setCategoryFilter(value)}
                className={`
                  filter-chip px-3 py-1.5 rounded-full text-xs font-medium transition-all
                  ${categoryFilter === value
                    ? 'filter-chip-active'
                    : 'text-verse-text-muted hover:text-verse-text hover:border-verse-border-light'
                  }
                `}
              >
                {label}
              </button>
            ))}
          </div>
        </div>
      </section>

      {loading ? (
        <LoadingState type="skeleton" />
      ) : error ? (
        <div className="glass-panel p-8 text-center space-y-3 animate-fade-in">
          <AlertCircle size={32} className="text-verse-red mx-auto" />
          <p className="text-verse-text font-medium">Failed to load issues</p>
          <p className="text-verse-text-muted text-sm">{error}</p>
          <button onClick={fetchIssues} className="btn-secondary text-sm mx-auto">
            Retry
          </button>
        </div>
      ) : filtered.length === 0 ? (
        <div className="glass-panel p-12 text-center space-y-3 animate-fade-in">
          <Shield size={44} className="text-verse-green mx-auto opacity-60" />
          <p className="text-verse-text font-medium text-lg">
            {issues.length === 0 ? 'No issues found' : 'No matching issues'}
          </p>
          <p className="text-verse-text-muted text-sm">
            {issues.length === 0
              ? 'Upload and validate episodes to see continuity checks here.'
              : 'Try adjusting the filters.'}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map((issue) => (
            <IssueCard
              key={issue.id}
              issue={issue}
              onResolve={handleResolve}
            />
          ))}
        </div>
      )}
    </div>
  );
}
